# Generated by Django 2.2.3 on 2019-07-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_time']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='accept',
        ),
    ]
